const ERROR_NOT_FOUND = 404;
const ERROR_CODE = 500;
const OK = 200;
const ERROR_VALIDATION = 400;
const ERROR_LOGIN = 401;

module.exports = {
  ERROR_CODE,
  ERROR_NOT_FOUND,
  ERROR_VALIDATION,
  OK,
  ERROR_LOGIN,
};
